version: '3'
services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "c/Users/ashwi/config:/etc/selenoid"
      - "var/run/docker.sock:/var/run/docker.sock"
      - "c/Users/ashwi/selenoid/video/:/opt/selenoid/video"
      - "c/Users/ashwi/selenoid/logs/:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/ashwi/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"

