package com.ash.enums;

public enum ConfigurationEnum {

	URL,
	PASSEDSTEPSSCREENSHOTS,
	FAILEDSTEPSSCREENSHOTS,
	SKIPPEDSTEPSSCREENSHOTS,
	INFOSTEPSSCREENSHOTS,
	OVERRIDEEXTENTREPORTS,
	RETRYFAILEDTESTS,
	RUNMODE
}
